plugins {
    id 'com.android.application'
}

android {
    compileSdk 35
    namespace "com.spoofer.har"

    defaultConfig {
        applicationId "com.spoofer.packagename"
        minSdk 28
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

repositories {
    google()
    mavenCentral()
    maven { url 'https://api.xposed.info/' }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'de.robv.android.xposed:api:82:sources'
}
